apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-deployment
  labels:
    app: vpa
spec:
  replicas: 2   # increased for HA
  selector:
    matchLabels:
      app: vpa
  template:
    metadata:
      labels:
        app: vpa
    spec:
      containers:
      - name: vpa-container
        image: harishnshetty/vpahpa:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: vpa-svc
  labels:
    app: vpa
spec:
  selector:
    app: vpa
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
